---
title: "Bellabeat Case Study"
author: "Zane Urbane"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

1. Load the packages

```{r setup, echo=FALSE}
install.packages("tidyverse")
library(tidyverse)
```

2. Load the data

```{r dataframes setup}
setwd("/cloud/project/input_bellabeat")

# Daily data
daily_activity <- read.csv("/cloud/project/input_bellabeat/dailyActivity_merged.csv")
daily_sleep <- read.csv("sleepDay_merged.csv")

# Hourly data
hourly_intensities <- read.csv("/cloud/project/input_bellabeat/hourlyIntensities_merged.csv")
hourly_steps <- read.csv("/cloud/project/input_bellabeat/hourlySteps_merged.csv")
hourly_calories <- read.csv("/cloud/project/input_bellabeat/hourlyCalories_merged.csv")

# Check for NA

sum(is.na(daily_activity))
sum(is.na(daily_sleep))
sum(is.na(hourly_intensities))
sum(is.na(hourly_steps))
sum(is.na(hourly_calories))

# Check for duplicates

sum(duplicated(daily_activity))
sum(duplicated(daily_sleep))
sum(duplicated(hourly_intensities))
sum(duplicated(hourly_steps))
sum(duplicated(hourly_calories))

# Manage the duplicates in daily_sleep dataframe

daily_sleep <- daily_sleep[!duplicated(daily_sleep), ]

sum(duplicated(daily_sleep)) #check result

```

3. Explore and clean the data

```{r view and clean daily data}

# View the daily data frames 
# Check how many unique participants are there in each dataframe

n_distinct(daily_activity$Id)
n_distinct(daily_sleep$Id)

# There are more participants in daily activity than in daily sleep records.
# Overview of the data sets - daily_activity

head(daily_activity)
glimpse(daily_activity)
summary(daily_activity)

# Column ActivityDate is recognized as a character (chr) type, so it needs to be changed to a date. And the Id column should be nominal type, as it is used as an index, not a numeric value.
daily_activity$ActivityDate <- as.Date(daily_activity$ActivityDate, format = "%m/%d/%Y")
daily_activity$Id <- as.character(daily_activity$Id)

# In this case columns about Distance is not revelant and won't be used in analysis.
daily_activity <- daily_activity[,-c(4:10)]

# Add a column with weekdays in daily_activity dataframe
daily_activity$Weekday <- weekdays(daily_activity$ActivityDate)

head(daily_activity) #checking

# Overview of the data sets - daily_sleep

head(daily_sleep)
glimpse(daily_sleep)
summary(daily_sleep)

# Column SleepDay is recognized as a character (chr) type so it needs to be changed to date. And Id column shoud be nominal type as is use as index not numeric value.
daily_sleep$SleepDay <- as.Date(daily_sleep$SleepDay, format = "%m/%d/%Y")
daily_sleep$Id <- as.character(daily_sleep$Id)

head(daily_sleep) #checking
```
```{r merge daily data}
# Merge daily activities data with sleep data for analysis together. 
# In daily activity data there are 940 rows, but in sleep data only 410 rows.
# I will use left join to keep all data and explore it later.

comb_daily_data <- left_join(daily_activity, daily_sleep, by= c("Id","ActivityDate" = "SleepDay"))

# Rename ActivityDate column as Date

colnames(comb_daily_data)[colnames(comb_daily_data) == "ActivityDate"] <- "Date"

head(comb_daily_data)
glimpse(comb_daily_data) #checking

# Check for NA, duplicates and count unique participiants

sum(is.na(comb_daily_data))
sum(duplicated(comb_daily_data))
n_distinct(comb_daily_data$Id)

# There is 2650 NA values. 
# NA is only in merged data in sleep column. Replace it with zero for calculations.

comb_daily_data[is.na(comb_daily_data)] <- 0

head(comb_daily_data)
glimpse(comb_daily_data) #checking

# daily_sleep columns changed data type to dbl, I will change it back to int.

comb_daily_data$TotalSleepRecords <- as.integer(comb_daily_data$TotalSleepRecords)
comb_daily_data$TotalMinutesAsleep <- as.integer(comb_daily_data$TotalMinutesAsleep)
comb_daily_data$TotalTimeInBed <- as.integer(comb_daily_data$TotalTimeInBed)

head(comb_daily_data) #checking

# Check for NA, duplicates and count unique participiants

sum(is.na(comb_daily_data))
sum(duplicated(comb_daily_data))
n_distinct(comb_daily_data$Id)

```
```{r explore and clean hourly data}
# View the hourly data frames 
# Check how many unique participants are there in each dataframe

n_distinct(hourly_calories$Id)
n_distinct(hourly_intensities$Id)
n_distinct(hourly_steps$Id)

# Overview of the data sets - hourly_calories

head(hourly_calories)
glimpse(hourly_calories)
summary(hourly_calories)

# Overview of the data sets - hourly_intensities

head(hourly_intensities)
glimpse(hourly_intensities)
summary(hourly_intensities)

# Overview of the data sets - hourly_steps

head(hourly_steps)
glimpse(hourly_steps)
summary(hourly_steps)

# Column ActivityHour is recognized as a character (chr) type, so it needs to be changed to a date in every dataset. And the Id column should be nominal type, as it is used as an index, not a numeric value.
hourly_calories$ActivityHour <- as.POSIXct(hourly_calories$ActivityHour, format = "%m/%d/%Y %I:%M:%S %p")
hourly_calories$Id <- as.character(hourly_calories$Id)
hourly_intensities$ActivityHour <- as.POSIXct(hourly_intensities$ActivityHour, format = "%m/%d/%Y %I:%M:%S %p")
hourly_intensities$Id <- as.character(hourly_intensities$Id)
hourly_steps$ActivityHour <- as.POSIXct(hourly_steps$ActivityHour, format = "%m/%d/%Y %I:%M:%S %p")
hourly_steps$Id <- as.character(hourly_steps$Id)

head(hourly_calories) #checking
head(hourly_intensities)
head(hourly_steps)
summary(hourly_calories)
```
```{r merge hourly activities}
# Merge hourly data together. In all 3 data sets ar 22099 rows, and columns: Id and ActivityHour

merge_1 <- merge(hourly_calories, hourly_intensities, by = c("Id", "ActivityHour"))
comb_hourly_data <- merge(merge_1, hourly_steps, by = c("Id", "ActivityHour"))

# Rename ActivityDate column as Date

colnames(comb_hourly_data)[colnames(comb_hourly_data) == "ActivityDate"] <- "Date"

head(comb_hourly_data)
glimpse(comb_hourly_data)
summary(comb_hourly_data) #checking

# Check for NA, duplicates and count unique participiants

sum(is.na(comb_hourly_data))
sum(duplicated(comb_hourly_data))
n_distinct(comb_hourly_data$Id)

# Add a column with weekdays in comb_hourly_data dataframe
comb_hourly_data$Weekday <- weekdays(comb_hourly_data$ActivityHour)

head(comb_hourly_data) #checking
```
4.Explore daily merge data.
```{r view merged daily data}
# I would like to understand how Fitbit users used the tracker.
# Did them used it all day long or only when excersising.
# There is 1440 min in a day so I will check thas data in time columns sum up or not.

comb_daily_data <- mutate(comb_daily_data, TotalMinutes = VeryActiveMinutes + FairlyActiveMinutes + LightlyActiveMinutes + SedentaryMinutes + TotalTimeInBed)

head(comb_daily_data)
summary(comb_daily_data$TotalMinutes)

# Check precise how much of records ar 1440 min a day
count_1440_minutes <- sum(comb_daily_data$TotalMinutes == 1440)
print(count_1440_minutes)

# 604 of 940 records include all day.

ggplot(comb_daily_data, aes(x = Date, y = Id, fill = TotalMinutes)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "blue") +
  labs(title = "Heatmap of Total Minutes by ID and Date",
       x = "Date", y = "ID", fill = "Total Minutes") +
  theme_minimal()

# There are users that have not used Fitbit tracker for all the period.
# It looks like that some minuts don't go to right date.
# That could be because the sleep data is daily and could refer to 2 dates.
# From heat map looks like last date could be incompleat.
# Lets look at average minutes per day 
Id_activity <- comb_daily_data %>%
  group_by(Id) %>%
  summarise(
    total_dates = n_distinct(Date),
    total_minutes = sum(TotalMinutes)
  ) %>%
  mutate(average_total_minutes = total_minutes / total_dates)%>%
  arrange(desc(average_total_minutes))

print(Id_activity)
summary(Id_activity)

# Average minutes for day is from 1322 to 1439 so sleeping time accuracy could be the cases.

# How many days partipics were involved
id_count <- Id_activity %>%
  group_by(total_dates) %>%
  summarise(id_count = n_distinct(Id))
print(id_count)


# And I want to see how looks those records, that don't have daily sleep records.

comb_data_no_sleep <- comb_daily_data[comb_daily_data$TotalSleepRecords == 0,]
ggplot(data=comb_data_no_sleep, aes(x=TotalMinutes, y=SedentaryMinutes)) + geom_point()

count_1440_minutes_no_sleep <- sum(comb_data_no_sleep$TotalMinutes == 1440)
print(count_1440_minutes_no_sleep)

# 478 from 530 records are 1440 min whitout sleep time.
# Looks like sleeping time is added to SedentaryMinutes.
# Maybe users needed to add it manually.

```

```{r daily activity analysis}
#For daily activities analysis I will use only data that includes sleeping data.
daily_analysis_data <- comb_daily_data %>%
  filter(TotalSleepRecords > 0)
#Add colomn with some activity time
daily_analysis_data <- mutate(daily_analysis_data, SomeActivity = VeryActiveMinutes + FairlyActiveMinutes + LightlyActiveMinutes)
#Add colomn with laying in bed time
daily_analysis_data <- mutate(daily_analysis_data, LayingMinutes = TotalTimeInBed - TotalMinutesAsleep)

head(daily_analysis_data)
summary(daily_analysis_data)

daily_analysis_data <- mutate(daily_analysis_data, SedetaryBedMinutes = LayingMinutes + SedentaryMinutes)

#There is still days whit SedentaryMinutes 1265.0, that means sleeping time is less than 3 hours. And Total minutes from min 323 un max 1799 min, but Median is just right 1440 min. 

ggplot(data=daily_analysis_data, aes(x=TotalSteps, y=SomeActivity)) + geom_smooth(method = "loess") + 
  labs(title = "Comparison of Steps VS Activity Time", x = "Total Steps", y = "Activity Time")
# More active minutes more steps.

ggplot(data=daily_analysis_data, aes(x=SedentaryMinutes, y=SomeActivity)) +
  geom_point()+
  geom_smooth(method = "loess") + 
  labs(title = "Comparison of SedentaryMinutes VS Activity Time", x = "Sedentary Time", y = "Activity Time")

daily_analysis_data$Weekday <- factor(daily_analysis_data$Weekday, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))

ggplot(data=daily_analysis_data, aes(x=Weekday, y=SedentaryMinutes, fill=SedentaryMinutes))+
  geom_bar(stat="identity")+
  labs(title="Daily Sedentary Minutes")

#Lets look at daily time distribution

sums_act <- colSums(daily_analysis_data[, c("VeryActiveMinutes", "FairlyActiveMinutes", "LightlyActiveMinutes", "SedentaryMinutes", "TotalMinutesAsleep", "LayingMinutes")])

total_sum_act <- sum(sums_act)

percentages_sum_act <- (sums_act / total_sum_act) * 100

avg_act <- colMeans(daily_analysis_data[, c("VeryActiveMinutes", "FairlyActiveMinutes", "LightlyActiveMinutes", "SedentaryMinutes", "TotalMinutesAsleep", "LayingMinutes")])

sum_daily_activites <- data.frame(
  Activity = names(sums_act),
  TotalTime = as.numeric(sums_act),
  PercentageOfTotal = percentages_sum_act,
  AvgTime = as.numeric(avg_act)
)

head(sum_daily_activites) #checking

ggplot(data=sum_daily_activites, aes(x=Activity, y=AvgTime))+
  geom_bar(stat="identity")+
  labs(title="Average Time in day for each activity")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Most of the time is spent as sedentary minutes.

#Explore activities by weekdays

avg_by_weekday <- daily_analysis_data %>%
  group_by(Weekday) %>%
  summarise(
    AvgVeryActiveMinutes = mean(VeryActiveMinutes, na.rm = TRUE),
    AvgFairlyActiveMinutes = mean(FairlyActiveMinutes, na.rm = TRUE),
    AvgLightlyActiveMinutes = mean(LightlyActiveMinutes, na.rm = TRUE),
    AvgSedentaryMinutes = mean(SedentaryMinutes, na.rm = TRUE),
    AvgTotalMinutesAsleep = mean(TotalMinutesAsleep, na.rm = TRUE),
    AvgLayingMinutes = mean(LayingMinutes, na.rm = TRUE)
  )

head(avg_by_weekday)
summary(avg_by_weekday)
```
5. Export files
```{r file export}
# Preparing and exporting files for analysis and presentation in Tableau

# Only data I will need and in long format

exp_daily_act <- daily_analysis_data %>%
  select(Id, Date, Weekday, VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, TotalMinutesAsleep, LayingMinutes) %>%
  pivot_longer(
    cols = c(VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, TotalMinutesAsleep, LayingMinutes),
    names_to = "ActivityType",
    values_to = "Minutes"
  )

head(exp_daily_act)
summary(exp_daily_act) #checking

write.csv(exp_daily_act, file = "/cloud/project/output_bellabeat/daily_data.csv",  row.names = FALSE)

# Export the Hourly data
write.csv(comb_hourly_data, file= "/cloud/project/output_bellabeat/comb_hourly_data.csv", row.names = FALSE)

#For summary
exp_summary_act <- daily_analysis_data %>%
  select(Id, Date, Weekday, SomeActivity, TotalMinutesAsleep, SedetaryBedMinutes) %>%
  pivot_longer(
    cols = c(SomeActivity, TotalMinutesAsleep, SedetaryBedMinutes),
    names_to = "ActivityType",
    values_to = "Minutes"
  )

head(exp_summary_act)
summary(exp_summary_act) #checking

# Export the Hourly data
write.csv(exp_summary_act, file= "/cloud/project/output_bellabeat/summary_act_data.csv", row.names = FALSE)
```

